#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
ENAMES="KAERHCPkaerhcp"
CNAMES="帥仕相俥傌炮兵將士象車馬包卒"
for i in {0..13} ; do
  ENAME="${ENAMES:$i:1}"
  CNAME="${CNAMES:$i:1}"
  ARENA_BOARD=${ARENA_BOARD//$ENAME/$CNAME}
done
BOARD=""
for i in {0..89} ; do
  CNAME="${ARENA_BOARD:$i:1}"
  if [ "$CNAME" = _ ] ; then
    case $i in
      0) CNAME="╚" ;;
      [1-8]) CNAME="╧" ;;
      9) CNAME="╝" ;;
      [1-7]0) CNAME="╟" ;;
      [1-7][123678]) CNAME="┼" ;;
      [1-7]4) CNAME="┤" ;;
      [1-7]5) CNAME="├" ;;
      [1-7]9) CNAME="╢" ;;
      80) CNAME="╔" ;;
      8[1-8]) CNAME="╤" ;;
      89) CNAME="╗" ;;
    esac
  fi
  BOARD="$BOARD$CNAME"
done
BOARD="$BOARD"${ARENA_BOARD:90}

PLAYER1="(Red)"
PLAYER2="(Black)"
if [ $((ARENA_MOVENO%2)) -eq 1 ] ; then # check if player1's turn
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER1=$PLAYER1"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  elif [ "${ARENA_STATUS:0:7}" = "INVALID" ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1"*"
  else
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  fi
  PLAYER2=$PLAYER2" "
else
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER2=$PLAYER2"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  elif [ "${ARENA_STATUS:0:7}" = "INVALID" ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2"*"
  else
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  fi
  PLAYER1=$PLAYER1" "
fi

DEADS="${BOARD:91}"
REDDEAD=""
BLACKDEAD=""
i=0
while [ $i -lt ${#DEADS} ] ; do
  DEAD=${DEADS:i:1}
  CNAMEX=${CNAMES%%${DEAD}*}
  [ ${#CNAMEX} -lt 7 ] && REDDEAD=${REDDEAD}${DEAD} || BLACKDEAD=${BLACKDEAD}${DEAD}
  let i++
done

if [ "${ARENA_THEME,,}" = log ] ; then
  [ -n "$ARENA_STATUS" ] && echo "${MESSAGE} ${ARENA_MOVENO} Moves."
else # default
  POSY="１２３４５６７８９"
  clear
  echo
  for y in {8..0} ; do
    echo -n ${POSY:y:1}" "
    for x in {0..9} ; do
      POS=$((y*10+x))
      echo -n ${BOARD:POS:1}
      if [ ${ARENA_BOARD:POS:1} = _ ] ; then
        echo -n " "
      fi
      if [ $x -ne 9 ] ; then
        if [ $y -eq 8 -o $y -eq 0 ] ; then
          echo -n "═"
        else
          [ $x -eq 4 ] && echo -n " " || echo -n "─"
        fi
      fi
    done
    case $y in
      8) echo -e "\t${ARENA_PLAYER1}${PLAYER1} vs. ${ARENA_PLAYER2}${PLAYER2}" ;;
      5) echo -e "\t${MESSAGE}" ;;
      2) echo -e "\t☠ : ${REDDEAD}" ;;
      1) echo -e "\t    ${BLACKDEAD}" ;;
      *) echo ;;
    esac
  done
  echo -en "   Ａ Ｂ Ｃ Ｄ Ｅ Ｆ Ｇ Ｈ Ｊ Ｋ\tMove No. ${ARENA_MOVENO}: "
fi
