#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
function piece {
  SEQ=$1
  PIECE=${ARENA_BOARD:SEQ:1}
  RNAMES="帥仕相俥傌炮兵"
  if [ $PIECE = _ ] ; then
    case $SEQ in
      0) PIECE="╚═" ;;
      [1-8]) PIECE="╧═" ;;
      9) PIECE="╝ " ;;
      [1-7]0) PIECE="╟─" ;;
      [1-7][123678]) PIECE="┼─" ;;
      [1-7]4) PIECE="┤ " ;;
      [1-7]5) PIECE="├─" ;;
      [1-7]9) PIECE="╢ " ;;
      80) PIECE="╔═" ;;
      8[1-8]) PIECE="╤═" ;;
      89) PIECE="╗ " ;;
    esac
    [ "${ARENA_MOVE:0:2}" = ${POSXS:SEQ%10:1}$((SEQ/10+1)) ] && PIECE="\e[103m$PIECE\e[43m"
  elif [ $RNAMES != ${RNAMES/$PIECE/} ] ; then
    [ "${ARENA_MOVE:2:2}" = ${POSXS:SEQ%10:1}$((SEQ/10+1)) ] && PIECE="\e[103;31m$PIECE\e[43;90m" || PIECE="\e[31m$PIECE\e[90m"
  else
    [ "${ARENA_MOVE:2:2}" = ${POSXS:SEQ%10:1}$((SEQ/10+1)) ] && PIECE="\e[103;30m$PIECE\e[43;90m" || PIECE="\e[30m$PIECE\e[90m"
  fi
  if [ $((SEQ%10)) -ne 9 ] ; then
    if [ $((SEQ/10%8)) -eq 0 ] ; then
      PIECE="$PIECE═"
    elif [ $((SEQ%10)) -ne 4 ] ; then
      PIECE="$PIECE─"
    else
      PIECE="$PIECE "
    fi
  fi
  echo -en "$PIECE" # need quote
}

POSXS="ABCDEFGHJK"
ENAMES="KAERHCPkaerhcp"
CNAMES="帥仕相俥傌炮兵將士象車馬包卒"
for i in {0..13} ; do
  ENAME="${ENAMES:$i:1}"
  CNAME="${CNAMES:$i:1}"
  ARENA_BOARD=${ARENA_BOARD//$ENAME/$CNAME}
done

PLAYER1="\e[31m⬤ \e[0m"
PLAYER2="◯ "
if [ $((ARENA_MOVENO%2)) -eq 1 ] ; then # check if player1's turn
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER1=$PLAYER1"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1"*"
  else
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER2=$PLAYER2" "
else
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER2=$PLAYER2"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2"*"
  else
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER1=$PLAYER1" "
fi

DEADS="${ARENA_BOARD:91}"
REDDEAD=""
BLACKDEAD=""
i=0
while [ $i -lt ${#DEADS} ] ; do
  DEAD=${DEADS:i:1}
  CNAMEX=${CNAMES%%${DEAD}*}
  [ ${#CNAMEX} -lt 7 ] && REDDEAD=${REDDEAD}${DEAD} || BLACKDEAD=${BLACKDEAD}${DEAD}
  let i++
done

if [ "${ARENA_THEME,,}" = log ] ; then
  [ -n "$ARENA_STATUS" ] && echo "$MESSAGE $ARENA_MOVENO Moves."
else # default
  POSY="１２３４５６７８９"
  clear
  for y in {8..0} ; do
    echo -en ${POSY:y:1}"\e[90;43m "
    for x in {0..9} ; do
      POS=$((y*10+x))
      echo -n "`piece $POS`" # need quote
    done
    echo -en " \e[0m"
    case $y in
      8) echo -e "\tXiang Qi" ;;
      6) echo -e "\t${ARENA_PLAYER1}${PLAYER1} vs. ${ARENA_PLAYER2}${PLAYER2}" ;;
      4) echo -e "\t${MESSAGE}" ;;
      2) echo -e "\t▥ : \e[107;31m${REDDEAD}\e[0m" ;;
      1) echo -e "\t    \e[107;30m${BLACKDEAD}\e[0m" ;;
      *) echo ;;
    esac
  done
  echo -en "   Ａ Ｂ Ｃ Ｄ Ｅ Ｆ Ｇ Ｈ Ｊ Ｋ\tMove No. ${ARENA_MOVENO}: "
fi
