#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018
POSXS="ABCDEFGHJKX" # X positions of board
DEADS="AERHCP"
until "$DATADIR/uis/$ARENA_GAME/get_valid_board" &>/dev/null ; do
  ARENA_MOVE=${POSXS:RANDOM%11:1}
  if [ $ARENA_MOVE = X ] ; then
    ARENA_MOVE=$ARENA_MOVE${DEADS:RANDOM%6:1}${POSXS:RANDOM%10:1}$((RANDOM%9+1))
  else
    ARENA_MOVE=$ARENA_MOVE$((RANDOM%9+1))${POSXS:RANDOM%10:1}$((RANDOM%9+1))
  fi
done
echo "$ARENA_MOVE"
