#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017

# let player2 choose color
if [ $ARENA_MOVENO -eq 0 ] ; then
  echo "Choose Red/Black for $ARENA_PLAYER2"
  exit 1
fi

# store the game board
if [ "${ARENA_STATUS:0:7}" != INVALID -a "${ARENA_STATUS:0:7}" != ILLEGAL ] ; then
  echo $ARENA_BOARD >> $ARENA_TEMP
fi

# if one player has no piece
BOARD=${ARENA_BOARD:0:32} # get living pieces
if [ "$BOARD" = "${BOARD^^}" -o "$BOARD" = "${BOARD,,}" ] ; then
  echo "ELIMINATION WINS !"
  exit 0
fi

# if no valid move
MOVES=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"`
if [ -z "$MOVES" ] ; then
  echo "STALEMATE WINS !"
  exit 0
fi

# if the game is draw
BOARD=${ARENA_BOARD:0:32} # get living board
[ $((ARENA_MOVENO%2)) -eq 1 ] && TURN="$ARENA_COLOR1" || TURN="$ARENA_COLOR2" # get color turn
LIVE=${BOARD//_/}
if [ ${#LIVE} -eq 2 ] ; then
  PIECE1=${LIVE:0:1}
  [ ${PIECE1^} = ${PIECE1} ] && COLOR1=Red || COLOR1=Black
  PIECE2=${LIVE:1:1}
  [ ${PIECE2^} = ${PIECE2} ] && COLOR2=Red || COLOR2=Black
  RANKS="KAERHCPkaerhcp"
  RANK1=${RANKS%%${PIECE1}*}
  RANK1=$((${#RANK1}%7))
  RANK2=${RANKS%%${PIECE2}*}
  RANK2=$((${#RANK2}%7))
  POS1=${BOARD%%${PIECE1}*}
  POS1=${#POS1}
  POS2=${BOARD%%${PIECE2}*}
  POS2=${#POS2}
  DISTX=$((POS2/8-POS1/8))
  DISTY=$((POS2%8-POS1%8))
  let DIST=${DISTX#-}+${DISTY#-} # get distance between pieces
  if [ "${LIVE^^}" = CC -o "${LIVE^^}" = CP -o "${LIVE^^}" = PC ] ; then
    echo "DRAW GAME !"
    exit 0
  elif [ "${LIVE^^}" = HH -a $((DIST%2)) -eq 1 ] ; then
    echo "DRAW GAME !"
    exit 0
  elif [ $RANK1 -ne $RANK2 -a $RANK1 -ne 3 -a $RANK1 -ne 4 -a $RANK2 -ne 3 -a $RANK2 -ne 4 ] ; then
    [ $RANK1 -lt $RANK2 -o $RANK1 -eq 6 -a $RANK2 -eq 0 ] && STRONGER=$COLOR1 || STRONGER=$COLOR2
    if [ "$TURN" = "$STRONGER" -a $((DIST%2)) -eq 0 ] ; then
      echo "DRAW GAME !"
      exit 0
    elif [ "$TURN" != "$STRONGER" -a $((DIST%2)) -eq 1 ] ; then
      echo "DRAW GAME !"
      exit 0
    fi
  fi
fi

# not the end of game
echo "$ARENA_STATUS" # still return last status
exit 1
