#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
DATADIR=`dirname "$0"`
export ARENA_UI=`basename "$DATADIR"`
DATADIR=`dirname "$DATADIR"`
export ARENA_GAME=`basename "$DATADIR"`
DATADIR=`dirname "$DATADIR"`
export DATADIR=`dirname "$DATADIR"`

export ARENA_PLAYER1="$1"
export ARENA_PLAYER2="$2"
export ARENA_THEME="$3"
export ARENA_BOARD="@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|"
export ARENA_BLACKER=0
export ARENA_MOVENO=1
export ARENA_MOVE=""
export ARENA_STATUS=""

until ARENA_STATUS=`"$DATADIR/uis/$ARENA_GAME/is_the_end" "$ARENA_BOARD" "$ARENA_MOVENO" "$ARENA_STATUS"` ; do
  "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/show_the_game" "$ARENA_BOARD" "$ARENA_MOVENO" "$ARENA_STATUS"
  [ $((ARENA_MOVENO%2)) -eq 1 ] && ARENA_PLAYER="$ARENA_PLAYER1" || ARENA_PLAYER="$ARENA_PLAYER2"
  if [ "$ARENA_PLAYER" = Human ] ; then
    sleep 1
    read ARENA_MOVE
    ARENA_MOVE=${ARENA_MOVE^^}
  else
    ARENA_MOVE=`"$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER/main" "$ARENA_BOARD" "$ARENA_MOVENO"`
    [ "$ARENA_THEME" != Log ] && echo "$ARENA_MOVE"
  fi
  if [ -n "$ARENA_MOVE" ] ; then
    ARENA_BOARD_NEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_board" "$ARENA_BOARD" "$ARENA_MOVENO" "$ARENA_MOVE"`
    if [ -z "$ARENA_BOARD_NEXT" ] ; then
      ARENA_STATUS="INVALID MOVE: $ARENA_MOVE"
      if [ "$ARENA_PLAYER" = "Human" ] ; then
        continue
      else
        break
      fi
    else
      ARENA_BOARD="$ARENA_BOARD_NEXT"
      ARENA_STATUS=""
      if [ "$ARENA_BLACKER" -eq 0 ] ; then
        [ "$ARENA_BOARD" = "${ARENA_BOARD^^}" ] && ARENA_BLACKER=2 || ARENA_BLACKER=1
      fi
    fi
  else
    ARENA_STATUS="MIDDLE WINS !"
    break
  fi
  let ARENA_MOVENO++
done
"$DATADIR/uis/$ARENA_GAME/$ARENA_UI/show_the_game" "$ARENA_BOARD" "$ARENA_MOVENO" "$ARENA_STATUS"
[ "$ARENA_THEME" != Log ] && echo "THE END"
