#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
function colorString {
  case $1 in
    bold) color='\e[1m' ;;
    red) color='\e[0;31m' ;;
    RED) color='\e[1;31m' ;;
    green) color='\e[0;32m' ;;
    GREEN) color='\e[1;32m' ;;
    yellow) color='\e[0;33m' ;;
    YELLOW) color='\e[1;33m' ;;
    blue) color='\e[0;34m' ;;
    BLUE) color='\e[1;34m' ;;
    magenta) color='\e[0;35m' ;;
    MAGENTA) color='\e[1;35m' ;;
    cyan) color='\e[0;36m' ;;
    CYAN) color='\e[1;36m' ;;
    gray) color='\e[0;37m' ;;
    GRAY) color='\e[1;37m' ;;
  esac
  shift
  echo -n "${color}$@"'\e[0m'
}

ENAMES="KAERHCPkaerhcp_@"
CNAMES="帥仕相俥傌炮兵將士象車馬包卒　＠"
for i in {0..15} ; do
  ENAME="${ENAMES:$i:1}"
  CNAME="${CNAMES:$i:1}"
  ARENA_BOARD=${ARENA_BOARD//$ENAME/$CNAME}
done

if [ $ARENA_BLACKER -eq 0 ] ; then
  PLAYER1="(?)"
  PLAYER2="(?)"
elif [ $ARENA_BLACKER -eq 1 ] ; then
  PLAYER1="(Black)"
  PLAYER2="(Red)"
else
  PLAYER1="(Red)"
  PLAYER2="(Black)"
fi
if [ $((ARENA_MOVENO%2)) -eq 1 ] ; then # check if player1's turn
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER1=$PLAYER1"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  elif [ "${ARENA_STATUS:0:7}" = "INVALID" ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1"*"
  else
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  fi
  PLAYER2=$PLAYER2" "
else
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER2=$PLAYER2"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  elif [ "${ARENA_STATUS:0:7}" = "INVALID" ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2"*"
  else
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  fi
  PLAYER1=$PLAYER1" "
fi

DEADS="${ARENA_BOARD:33}"
REDDEAD=""
BLACKDEAD=""
i=0
while [ $i -lt ${#DEADS} ] ; do
  DEAD=${DEADS:i:1}
  CNAMEX=${CNAMES%%${DEAD}*}
  [ ${#CNAMEX} -lt 7 ] && REDDEAD=${REDDEAD}${DEAD} || BLACKDEAD=${BLACKDEAD}${DEAD}
  let i++
done

if [ "$ARENA_THEME" = "Roll" ] ; then
  echo
  echo -e "   ╔ ═ ╤ ═ ╤ ═ ╤ ═ ╤ ═ ╤ ═ ╤ ═ ╤ ═ ╗ \t${ARENA_PLAYER1}${PLAYER1} vs. ${ARENA_PLAYER2}${PLAYER2}"
  echo -e "４ ║ "${ARENA_BOARD:24:1}"│ "${ARENA_BOARD:25:1}"│ "${ARENA_BOARD:26:1}"│ "${ARENA_BOARD:27:1}"│ "${ARENA_BOARD:28:1}"│ "${ARENA_BOARD:29:1}"│ "${ARENA_BOARD:30:1}"│ "${ARENA_BOARD:31:1}"║ "
  echo -e "   ╟ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ╢ "
  echo -e "３ ║ "${ARENA_BOARD:16:1}"│ "${ARENA_BOARD:17:1}"│ "${ARENA_BOARD:18:1}"│ "${ARENA_BOARD:19:1}"│ "${ARENA_BOARD:20:1}"│ "${ARENA_BOARD:21:1}"│ "${ARENA_BOARD:22:1}"│ "${ARENA_BOARD:23:1}"║ "
  echo -e "   ╟ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ╢ \t${MESSAGE}"
  echo -e "２ ║ "${ARENA_BOARD:8:1}"│ "${ARENA_BOARD:9:1}"│ "${ARENA_BOARD:10:1}"│ "${ARENA_BOARD:11:1}"│ "${ARENA_BOARD:12:1}"│ "${ARENA_BOARD:13:1}"│ "${ARENA_BOARD:14:1}"│ "${ARENA_BOARD:15:1}"║ "
  echo -e "   ╟ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ┼ ─ ╢ \t☠ : ${REDDEAD}"
  echo -e "１ ║ "${ARENA_BOARD:0:1}"│ "${ARENA_BOARD:1:1}"│ "${ARENA_BOARD:2:1}"│ "${ARENA_BOARD:3:1}"│ "${ARENA_BOARD:4:1}"│ "${ARENA_BOARD:5:1}"│ "${ARENA_BOARD:6:1}"│ "${ARENA_BOARD:7:1}"║ \t    ${BLACKDEAD}"
  echo -e "   ╚ ═ ╧ ═ ╧ ═ ╧ ═ ╧ ═ ╧ ═ ╧ ═ ╧ ═ ╝ "  
  echo -en "     Ａ  Ｂ  Ｃ  Ｄ  Ｅ  Ｆ  Ｇ  Ｈ  \tMove No. ${ARENA_MOVENO}: "
elif [ "$ARENA_THEME" = Log ] ; then
  [ -n "$ARENA_STATUS" ] && echo "${MESSAGE} ${ARENA_MOVENO} Moves."
fi
