#!/usr/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018
POSXS="ABCDEFGHJ"

MOVEX1=`printf %d \'${ARENA_MOVE:0:1}`
MOVEY1=`printf %d \'${ARENA_MOVE:1:1}`
MOVEX2=`printf %d \'${ARENA_MOVE:3:1}`
MOVEY2=`printf %d \'${ARENA_MOVE:4:1}`

MOVEX1=$(((MOVEX1-36)/4))
MOVEY1=$(((MOVEY1-34)/2))
MOVEX2=$(((MOVEX2-36)/4))
MOVEY2=$(((MOVEY2-34)/2))

MOVE=${POSXS:MOVEX1:1}$((5-MOVEY1))${POSXS:MOVEX2:1}$((5-MOVEY2))
echo $MOVE
