#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018
shopt -s extglob
ARENA_MATCH=$1 # name of match file
ARENA_PLAYER1=$2 # name of player1
ARENA_PLAYER2=$3 # name of player2
ARENA_PLAYER3=$4 # name of player3
ARENA_GAME="" # game type from match file
ARENA_UI="" # game ui from match file
ARENA_THEME="" # ui theme from match file
[ "$0" = "./tossug-arena" ] && DATADIR="$PWD" || DATADIR=/usr/share/tossug-arena
RANDOM=`date +%s` # set random seed

if [ $# -eq 0 ] ; then
  echo "TOSSUG Arena: Gamelets Arena for AI Players"
  echo "Usage:"
  echo -e "\ttossug-arena MATCH[-log] [ PLAYER1 [ PLAYER2 [ PLAYER3 ]]]"
  echo
  echo "available MATCHs:"
  cd "$DATADIR/matches"
  echo -e "\t"`ls !(Human*|*-log)`
  echo "available PLAYERs: (Human as reserved default)"
  cd "$DATADIR/players"
  for i in * ; do
    echo -en "\tfor $i: "
    cd "$DATADIR/players/$i"
    for j in * ; do
      echo -n "$j "
    done
    echo
  done
  exit 1
fi

if ! [ -f "$DATADIR/matches/$ARENA_MATCH" ] ; then
  echo "match file: $DATADIR/matches/$ARENA_MATCH not found."
  exit 1
fi
source "$DATADIR/matches/$ARENA_MATCH"
if ! [ -x "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/main" ] ; then
  echo "ui file: $DATADIR/uis/$ARENA_GAME/$ARENA_UI/main not found."
  exit 1
fi

if [ -z "$ARENA_PLAYER1" -o "${ARENA_PLAYER1,,}" = human ] ; then
  ARENA_PLAYER1=Human1
fi
if [ -z "$ARENA_PLAYER2" -o "${ARENA_PLAYER2,,}" = human ] ; then
  ARENA_PLAYER2=Human2
fi
if [ -z "$ARENA_PLAYER3" -o "${ARENA_PLAYER3,,}" = human ] ; then
  ARENA_PLAYER3=Human3
fi

exec "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/main" "$ARENA_THEME" "$ARENA_PLAYER1" "$ARENA_PLAYER2" "$ARENA_PLAYER3"
