#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
shopt -s extglob
ARENA_ROUND=$1 # name of round file
ARENA_PLAYER1=$2 # name of player1
ARENA_PLAYER2=$3 # name of player2
ARENA_PLAYER3=$4 # name of player3
ARENA_GAME="" # game type from round file
ARENA_UI="" # game ui from round file
ARENA_THEME="" # ui theme from round file
[ "$0" = "./tossug-arena" ] && DATADIR="$PWD" || DATADIR=/usr/share/tossug-arena
RANDOM=`date +%s` # set random seed

if [ $# -eq 0 ] ; then
  echo "TOSSUG Arena: Gamelets Arena for AI Players"
  echo "Usage:"
  echo -e "\ttossug-arena ROUND[-log] [ PLAYER1 [ PLAYER2 [ PLAYER3 ]]]"
  echo
  echo "available ROUNDs:"
  cd "$DATADIR/rounds"
  echo -e "\t"`ls !(*-log)`
  echo "available PLAYERs: (Human as reserved default)"
  cd "$DATADIR/players"
  for i in * ; do
    echo -en "\tfor $i: "
    cd "$DATADIR/players/$i"
    for j in * ; do
      echo -n "$j "
    done
    echo
  done
  exit 1
fi

if ! [ -f "$DATADIR/rounds/$ARENA_ROUND" ] ; then
  echo "round file: $DATADIR/rounds/$ARENA_ROUND not found."
  exit 1
fi
source "$DATADIR/rounds/$ARENA_ROUND"
if ! [ -x "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/main" ] ; then
  echo "ui path: $DATADIR/uis/$ARENA_GAME/$ARENA_UI/main not found."
  exit 1
fi

if [ -z "$ARENA_PLAYER1" -o "${ARENA_PLAYER1,,}" = human ] ; then
  ARENA_PLAYER1=Human
elif ! [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER1/main" ] ; then
  echo "player path: $DATADIR/players/$ARENA_GAME/$ARENA_PLAYER1/main not found."
  exit 1
fi
if [ -z "$ARENA_PLAYER2" -o "${ARENA_PLAYER2,,}" = human ] ; then
  ARENA_PLAYER2=Human
elif ! [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER2/main" ] ; then
  echo "player path: $DATADIR/players/$ARENA_GAME/$ARENA_PLAYER2/main not found."
  exit 1
fi
if [ -z "$ARENA_PLAYER3" -o "${ARENA_PLAYER3,,}" = human ] ; then
  ARENA_PLAYER3=Human
elif ! [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER3/main" ] ; then
  echo "player path: $DATADIR/players/$ARENA_GAME/$ARENA_PLAYER3/main not found."
  exit 1
fi

exec "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/main" "$ARENA_THEME" "$ARENA_PLAYER1" "$ARENA_PLAYER2" "$ARENA_PLAYER3"
