#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
DATADIR=`dirname "$0"`
export ARENA_UI=`basename "$DATADIR"`
DATADIR=`dirname "$DATADIR"`
export ARENA_GAME=`basename "$DATADIR"`
DATADIR=`dirname "$DATADIR"`
export DATADIR=`dirname "$DATADIR"`

export ARENA_THEME="$1"
export ARENA_PLAYER1="$2"
export ARENA_PLAYER2="$3"
export ARENA_PLAYER3="$4"
export ARENA_COLOR1=""
export ARENA_COLOR2=""
export ARENA_COLOR3=""
export ARENA_MOVENO=1
export ARENA_MOVE=""
export ARENA_STATUS=""
export ARENA_TEMP=`mktemp`
export ARENA_BOARD="@@@@_@@@@@@@@_@@@@_________@@@@_@@@@@@@@_@@@@/"

until ARENA_STATUS=`"$DATADIR/uis/$ARENA_GAME/is_the_end"` ; do
  "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/show_the_game"
  if [ $((ARENA_MOVENO%3)) -eq 1 ] ; then
    ARENA_PLAYER="$ARENA_PLAYER1"
  elif [ $((ARENA_MOVENO%3)) -eq 2 ] ; then
    ARENA_PLAYER="$ARENA_PLAYER2"
  else
    ARENA_PLAYER="$ARENA_PLAYER3"
  fi
  if [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER/main" -a "${ARENA_PLAYER:0:5}" != Human ] ; then
    ARENA_MOVE=`"$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER/main"`
    [ "${ARENA_THEME,,}" != log ] && echo -e "$ARENA_MOVE\e[0m"
  else
    read ARENA_MOVE
    echo -en "\e[0m"
    ARENA_MOVE=${ARENA_MOVE^^}
  fi
  if [ -n "$ARENA_MOVE" ] ; then
    ARENA_BOARD_NEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_board"`
    if [ -z "$ARENA_BOARD_NEXT" ] ; then
      if [ "${ARENA_STATUS:0:7}" = INVALID ] ; then
        ARENA_STATUS="MIDDLE WINS !"
        break
      else
        ARENA_STATUS="INVALID MOVE: $ARENA_MOVE"
        continue
      fi
    elif grep -Pz $ARENA_BOARD'\n'$ARENA_BOARD_NEXT $ARENA_TEMP &>/dev/null ; then
      if [ "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
        ARENA_STATUS="MIDDLE WINS !"
        break
      else
        ARENA_STATUS="ILLEGAL MOVE: $ARENA_MOVE"
        continue
      fi
    else
      ARENA_BOARD="$ARENA_BOARD_NEXT"
      ARENA_STATUS=""
      if [ -z "$ARENA_COLOR1" ] ; then
        for i in A E R H C ; do
          [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] && ARENA_COLOR1="Red"
        done
        for i in a e r h c ; do
          [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] && ARENA_COLOR1="Black"
        done
        for i in K k P p ; do
          [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] && ARENA_COLOR1="Blue"
        done
      elif [ -z "$ARENA_COLOR2" -a $((ARENA_MOVENO%3)) -eq 2 ] ; then
        if [ "$ARENA_COLOR1" != Red ] ; then
          for i in A E R H C ; do
            if [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] ; then
              ARENA_COLOR2="Red"
              [ "$ARENA_COLOR1" = Black ] && ARENA_COLOR3="Blue" || ARENA_COLOR3="Black"
              break
            fi
          done
        fi
        if [ "$ARENA_COLOR1" != Black ] ; then
          for i in a e r h c ; do
            if [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] ; then
              ARENA_COLOR2="Black"
              [ "$ARENA_COLOR1" = Red ] && ARENA_COLOR3="Blue" || ARENA_COLOR3="Red"
              break
            fi
          done
        fi
        if [ "$ARENA_COLOR1" != Blue ] ; then
          for i in K k P p ; do
            if [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] ; then
              ARENA_COLOR2="Blue"
              [ "$ARENA_COLOR1" = Black ] && ARENA_COLOR3="Red" || ARENA_COLOR3="Black"
              break
            fi
          done
        fi
      elif [ -z "$ARENA_COLOR3" -a $((ARENA_MOVENO%3)) -eq 0 ] ; then
        if [ "$ARENA_COLOR1" != Red ] ; then
          for i in A E R H C ; do
            if [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] ; then
              ARENA_COLOR3="Red"
              [ "$ARENA_COLOR1" = Black ] && ARENA_COLOR2="Blue" || ARENA_COLOR2="Black"
              break
            fi
          done
        fi
        if [ "$ARENA_COLOR1" != Black ] ; then
          for i in a e r h c ; do
            if [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] ; then
              ARENA_COLOR3="Black"
              [ "$ARENA_COLOR1" = Red ] && ARENA_COLOR2="Blue" || ARENA_COLOR2="Red"
              break
            fi
          done
        fi
        if [ "$ARENA_COLOR1" != Blue ] ; then
          for i in K k P p ; do
            if [ "$ARENA_BOARD" != "${ARENA_BOARD/$i/}" ] ; then
              ARENA_COLOR3="Blue"
              [ "$ARENA_COLOR1" = Black ] && ARENA_COLOR2="Red" || ARENA_COLOR2="Black"
              break
            fi
          done
        fi
      fi
    fi
  else
    if [ "$ARENA_STATUS" = "STALEMATE PASS !" ] ; then
      ARENA_STATUS="STALEMATE WINS !"
      break
    else
      ARENA_STATUS="STALEMATE PASS !"
    fi
  fi
  let ARENA_MOVENO++
done
"$DATADIR/uis/$ARENA_GAME/$ARENA_UI/show_the_game"
[ "${ARENA_THEME,,}" != log ] && echo -e "THE END\e[0m"
