#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
function piece {
  SEQ=$1
  PIECE=${ARENA_BOARD:SEQ:1}
  POSX=${POSXS:SEQ%9:1}
  POSY=$((SEQ/9+1))
  RNAMES="仕相俥傌炮"
  BNAMES="士象車馬包"
  if [ $PIECE = _ ] ; then
    case $POSX$POSY in
      A1) PIECE="╚═" ;;
      [B-H]1) PIECE="╧═" ;;
      J1) PIECE="╝ " ;;
      A[2-4]) PIECE="╟─" ;;
      [B-H][2-4]) PIECE="┼─" ;;
      J[2-4]) PIECE="╢ " ;;
      A5) PIECE="╔═" ;;
      [B-H]5) PIECE="╤═" ;;
      J5) PIECE="╗ " ;;
    esac
    [ "${ARENA_MOVE:0:2}" = $POSX$POSY ] && PIECE="\e[103m$PIECE\e[43m"
  elif [ $PIECE = @ ] ; then
    PIECE="\e[32m⬤ \e[90m"
  elif [ $RNAMES != ${RNAMES/$PIECE/} ] ; then
    [ "${ARENA_MOVE:2:2}" = $POSX$POSY ] && PIECE="\e[103;31m$PIECE\e[43;90m" || PIECE="\e[31m$PIECE\e[90m"
  elif [ $BNAMES != ${BNAMES/$PIECE/} ] ; then
    [ "${ARENA_MOVE:2:2}" = $POSX$POSY ] && PIECE="\e[103;30m$PIECE\e[43;90m" || PIECE="\e[30m$PIECE\e[90m"
  else
    [ "${ARENA_MOVE:2:2}" = $POSX$POSY ] && PIECE="\e[103;34m$PIECE\e[43;90m" || PIECE="\e[34m$PIECE\e[90m"
  fi
  echo -en "$PIECE" # need quote
}

function color {
  [ "$1" = Red ] && echo -n '\e[31m⬤ \e[0m'
  [ "$1" = Black ] && echo -n '◯ '
  [ "$1" = Blue ] && echo -n '\e[34m⬤ \e[0m'
}

POSXS="ABCDEFGHJ"
ENAMES="AERHCaerhcKkPp"
CNAMES="仕相俥傌炮士象車馬包帥將兵卒"
for i in {0..13} ; do
  ENAME="${ENAMES:$i:1}"
  CNAME="${CNAMES:$i:1}"
  ARENA_BOARD=${ARENA_BOARD//$ENAME/$CNAME}
done

[ -z "$ARENA_COLOR1" ] && PLAYER1="？" || PLAYER1=`color $ARENA_COLOR1`
[ -z "$ARENA_COLOR2" ] && PLAYER2="？" || PLAYER2=`color $ARENA_COLOR2`
[ -z "$ARENA_COLOR3" ] && PLAYER3="？" || PLAYER3=`color $ARENA_COLOR3`
if [ $((ARENA_MOVENO%3)) -eq 1 ] ; then # check if player1's turn
  if [ -z "$ARENA_STATUS" ] ; then
    PLAYER=""
    PLAYER1=$PLAYER1"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    PLAYER=""
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "$ARENA_STATUS" = "STALEMATE PASS !" ] ; then
    PLAYER="$ARENA_PLAYER3 $PLAYER3"
    PLAYER1=$PLAYER1"*"
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    PLAYER="$ARENA_PLAYER1 $PLAYER1"
    PLAYER1=$PLAYER1"*"
  else
    PLAYER="$ARENA_PLAYER3 $PLAYER3"
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER2=$PLAYER2" "
  PLAYER3=$PLAYER3" "
elif [ $((ARENA_MOVENO%3)) -eq 2 ] ; then
  if [ -z "$ARENA_STATUS" ] ; then
    PLAYER=""
    PLAYER2=$PLAYER2"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    PLAYER=""
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "$ARENA_STATUS" = "STALEMATE PASS !" ] ; then
    PLAYER="$ARENA_PLAYER1 $PLAYER1"
    PLAYER2=$PLAYER2"*"
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    PLAYER="$ARENA_PLAYER2 $PLAYER2"
    PLAYER2=$PLAYER2"*"
  else
    PLAYER="$ARENA_PLAYER1 $PLAYER1"
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER1=$PLAYER1" "
  PLAYER3=$PLAYER3" "
else
  if [ -z "$ARENA_STATUS" ] ; then
    PLAYER=""
    PLAYER3=$PLAYER3"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    PLAYER=""
    PLAYER3=$PLAYER3" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "${ARENA_STATUS}" = "STALEMATE PASS !" ] ; then
    PLAYER="$ARENA_PLAYER2 $PLAYER2"
    PLAYER3=$PLAYER3"*"
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    PLAYER="$ARENA_PLAYER3 $PLAYER3"
    PLAYER3=$PLAYER3"*"
  else
    PLAYER="$ARENA_PLAYER2 $PLAYER2"
    PLAYER3=$PLAYER3" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER1=$PLAYER1" "
  PLAYER2=$PLAYER2" "
fi

DEADS="${ARENA_BOARD:46}"
REDDEAD=""
BLACKDEAD=""
BLUEDEAD=""
i=0
while [ $i -lt ${#DEADS} ] ; do
  DEAD=${DEADS:i:1}
  CNAMEX=${CNAMES%%${DEAD}*}
  if [ ${#CNAMEX} -gt 4 ] ; then
    [ ${#CNAMEX} -gt 9 ] && BLUEDEAD=$BLUEDEAD$DEAD || BLACKDEAD=$BLACKDEAD$DEAD
  else
    REDDEAD=$REDDEAD$DEAD
  fi
  let i++
done

if [ "${ARENA_THEME,,}" = log ] ; then
  [ "$ARENA_STATUS" != "${ARENA_STATUS/WINS/}" ] && echo "$PLAYER $ARENA_STATUS $ARENA_MOVENO Moves."
else # default
  clear
  echo -e "  $ARENA_PLAYER1 $PLAYER1 vs. $ARENA_PLAYER2 $PLAYER2 vs. $ARENA_PLAYER3 $PLAYER3"
  echo -e "５\e[90;43m "`piece 36`"══"`piece 37`"══"`piece 38`"══"`piece 39`"══"`piece 40`"══"`piece 41`"══"`piece 42`"══"`piece 43`"══"`piece 44`"\e[0m"
  echo -e "  \e[90;43m ║   │   │   │   │   │   │   │   ║ \e[0m\t\e[94mThree Kingdoms Xiang Qi\e[0m"
  echo -e "４\e[90;43m "`piece 27`"──"`piece 28`"──"`piece 29`"──"`piece 30`"──"`piece 31`"──"`piece 32`"──"`piece 33`"──"`piece 34`"──"`piece 35`"\e[0m"
  echo -e "  \e[90;43m ║   │   │   │   │   │   │   │   ║ \e[0m\t$PLAYER \e[95m$ARENA_STATUS\e[0m"
  echo -e "３\e[90;43m "`piece 18`"──"`piece 19`"──"`piece 20`"──"`piece 21`"──"`piece 22`"──"`piece 23`"──"`piece 24`"──"`piece 25`"──"`piece 26`"\e[0m"
  echo -e "  \e[90;43m ║   │   │   │   │   │   │   │   ║ \e[0m\t▥ : \e[107;31m$REDDEAD\e[0m"
  echo -e "２\e[90;43m "`piece 9`"──"`piece 10`"──"`piece 11`"──"`piece 12`"──"`piece 13`"──"`piece 14`"──"`piece 15`"──"`piece 16`"──"`piece 17`"\e[0m\t    \e[107;30m$BLACKDEAD\e[0m"
  echo -e "  \e[90;43m ║   │   │   │   │   │   │   │   ║ \e[0m\t    \e[107;34m$BLUEDEAD\e[0m"
  echo -e "１\e[90;43m "`piece 0`"══"`piece 1`"══"`piece 2`"══"`piece 3`"══"`piece 4`"══"`piece 5`"══"`piece 6`"══"`piece 7`"══"`piece 8`"\e[0m"
  echo -en "   Ａ  Ｂ  Ｃ  Ｄ  Ｅ  Ｆ  Ｇ  Ｈ  Ｊ  \tMove No. $ARENA_MOVENO: \e[93m"
fi
