#!/usr/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018

# store the game board
if [ "${ARENA_STATUS:0:7}" != INVALID -a "${ARENA_STATUS:0:7}" != ILLEGAL ] ; then
  echo $ARENA_BOARD >> $ARENA_TEMP
fi

# if one king is dead
BOARD=${ARENA_BOARD:91} # get dead pieces
if [ "$BOARD" != "${BOARD/K/}" -o "$BOARD" != "${BOARD/k/}" ] ; then
  echo "CHECKMATE WINS !"
  exit 0
fi

# if no valid move
MOVES=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"`
if [ -z "$MOVES" ] ; then
  echo "STALEMATE WINS !"
  exit 0
fi

# not the end of game
echo "$ARENA_STATUS" # still return last status
exit 1
