#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017

# if no valid move
MOVES=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"`
if [ -z "$MOVES" ] ; then
  let ARENA_MOVENO++
  MOVES=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"`
  if [ -z "$MOVES" ] ; then
    echo "ELIMINATION WINS !"
    exit 0
  fi
fi

# if the game is draw
if [ `grep -c "$ARENA_BOARD" $ARENA_TEMP` -eq 10 ] ; then # not sure
  echo "DRAW GAME !"
  exit 0
elif [ "${ARENA_STATUS:0:7}" != "INVALID" ] ; then
  echo "$ARENA_BOARD" >> $ARENA_TEMP
fi

# not the end of game
echo "$ARENA_STATUS" # still return last status
exit 1
