#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
BOARD=$1 # current game board
MOVENO=$2 # current move no.
MOVESNEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves" "$BOARD" "$MOVENO"` # next valid moves
MOVEINDEX=$((${#MOVESNEXT}/5))
MOVE=${MOVESNEXT:(RANDOM%MOVEINDEX)*5:4}
echo ${MOVE}