#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
POSXS="ABCDEFGH"
RANKS="KAERHCPkaerhcp"
[ $((ARENA_MOVENO%2)) -eq 1 ] && TURN=$ARENA_COLOR1 || TURN=$ARENA_COLOR2 # get color turn

MOVES=""
for y in {0..3} ; do
  for x in {0..7} ; do
    let SEQ=y*8+x
    POS1=${POSXS:x:1}$((y+1))
    PIECE1=${ARENA_BOARD:SEQ:1}
    if [ $PIECE1 = _ ] ; then
      continue
    elif [ $PIECE1 = @ ] ; then
      MOVES="${MOVES}${POS1}${POS1} "
      continue
    else
      [ $PIECE1 = ${PIECE1^} ] && COLOR1=Red || COLOR1=Black
      [ $COLOR1 != $TURN ] && continue
    fi
    
    for z in 1,0 0,1 -1,0 0,-1 ; do
      let DELTAX=${z%,*} DELTAY=${z#*,}
      let NEWX=x+DELTAX NEWY=y+DELTAY
      [ $NEWX -lt 0 -o $NEWX -gt 7 -o $NEWY -lt 0 -o $NEWY -gt 3 ] && continue
      PIECE2=${ARENA_BOARD:NEWY*8+NEWX:1}
      POS2=${POSXS:NEWX:1}$((NEWY+1))
      if [ $PIECE2 = _ ] ; then
        MOVES="${MOVES}${POS1}${POS2} "
      elif [ $PIECE2 != @ ] ; then
        [ $PIECE2 = ${PIECE2^} ] && COLOR2=Red || COLOR2=Black
        if [ $COLOR2 != $TURN ] ; then
          RANK1=${RANKS%%${PIECE1}*}
          RANK1=$((${#RANK1}%7))
          RANK2=${RANKS%%${PIECE2}*}
          RANK2=$((${#RANK2}%7))
          case $RANK1 in
            0) [ $RANK2 -ne 6 ] && MOVES="${MOVES}${POS1}${POS2} " ;;
            [1-4]) [ $RANK2 -ge $RANK1 ] && MOVES="${MOVES}${POS1}${POS2} " ;;
            6) [ $RANK2 -eq 0 -o $RANK2 -eq 6 ] && MOVES="${MOVES}${POS1}${POS2} " ;;
          esac
        fi
      fi
      if [ ${PIECE1^} = C ] ; then
        MIDDLE=0
        while [ $NEWX -ge 0 -a $NEWX -lt 8 -a $NEWY -ge 0 -a $NEWY -lt 4 ] ; do
          PIECE2=${ARENA_BOARD:NEWY*8+NEWX:1}
          if [ $PIECE2 = _ ] ; then
            let NEWX+=DELTAX NEWY+=DELTAY
          else
            if [ $MIDDLE -eq 0 ] ; then
              MIDDLE=1
              let NEWX+=DELTAX NEWY+=DELTAY
            else
              [ $PIECE2 = @ ] && break
              [ $PIECE2 = ${PIECE2^} ] && COLOR2=Red || COLOR2=Black
              [ $COLOR2 = $TURN ] && break
              POS2=${POSXS:NEWX:1}$((NEWY+1))
              MOVES="${MOVES}${POS1}${POS2} "
              break
            fi
          fi
        done
      fi
    done
  done
done

echo "$MOVES" # need quote
