#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
echo -ne "\e[?1000h" # enable mouse
DATADIR=`dirname "$0"`
export ARENA_UI=`basename "$DATADIR"`
DATADIR=`dirname "$DATADIR"`
export ARENA_GAME=`basename "$DATADIR"`
DATADIR=`dirname "$DATADIR"`
export DATADIR=`dirname "$DATADIR"`

export ARENA_THEME="$1"
export ARENA_PLAYER1="$2"
export ARENA_PLAYER2="$3"
export ARENA_COLOR1=""
export ARENA_COLOR2=""
export ARENA_MOVENO=0
export ARENA_MOVE=""
export ARENA_STATUS=""
export ARENA_TEMP=`mktemp`
export ARENA_BOARD=`"$DATADIR/uis/$ARENA_GAME/get_valid_board"`

until ARENA_STATUS=`"$DATADIR/uis/$ARENA_GAME/is_the_end"` ; do
  "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/show_the_game"
  [ $((ARENA_MOVENO%2)) -eq 1 ] && ARENA_PLAYER="$ARENA_PLAYER1" || ARENA_PLAYER="$ARENA_PLAYER2"
  if [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER/main" -a "${ARENA_PLAYER:0:5}" != Human ] ; then
    ARENA_MOVE=`"$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER/main"`
    [ "${ARENA_THEME,,}" != log ] && echo -e "$ARENA_MOVE\e[0m"
  else
    read ARENA_MOVE
    echo -en "\e[0m"
    ARENA_MOVE=${ARENA_MOVE^^}
  fi
  if [ -n "$ARENA_MOVE" ] ; then
    if [ $ARENA_MOVENO -eq 0 ] ; then
      if [ ${ARENA_MOVE:0:1} = B ] ; then
        ARENA_COLOR1="Red"
        ARENA_COLOR2="Black"
      else
        ARENA_COLOR1="Black"
        ARENA_COLOR2="Red"
      fi
      ARENA_STATUS=""
    else
      ARENA_BOARD_NEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_board"`
      if [ -z "$ARENA_BOARD_NEXT" ] ; then
        if [ "${ARENA_STATUS:0:7}" = INVALID ] ; then
          ARENA_STATUS="MIDDLE WINS !"
          break
        else
          ARENA_STATUS="INVALID MOVE: $ARENA_MOVE"
          continue
        fi
      elif grep -Pz $ARENA_BOARD'\n'$ARENA_BOARD_NEXT $ARENA_TEMP &>/dev/null ; then
        if [ "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
          ARENA_STATUS="MIDDLE WINS !"
          break
        else
          ARENA_STATUS="ILLEGAL MOVE: $ARENA_MOVE"
          continue
        fi
      else
        ARENA_BOARD="$ARENA_BOARD_NEXT"
        ARENA_STATUS=""
      fi
    fi
  else
    ARENA_STATUS="MIDDLE WINS !"
    break
  fi
  let ARENA_MOVENO++
done
"$DATADIR/uis/$ARENA_GAME/$ARENA_UI/show_the_game"
[ "${ARENA_THEME,,}" != log ] && echo -e "THE END\e[0m\e[?1000l"
