#!/usr/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018
function piece {
  SEQ=$1
  PIECE=${ARENA_BOARD:SEQ:1}
  RNAMES="帥仕相俥傌炮兵"
  if [ $PIECE = _ ] ; then
    [ "${ARENA_MOVE:0:2}" = ${POSXS:SEQ%8:1}$((SEQ/8+1)) ] && echo -en "\e[103m　\e[43m" || echo -n "　"
  elif [ $RNAMES != ${RNAMES/$PIECE/} ] ; then
    [ "${ARENA_MOVE:2:2}" = ${POSXS:SEQ%8:1}$((SEQ/8+1)) ] && echo -en "\e[103;31m$PIECE\e[43;90m" || echo -n "\e[31m$PIECE\e[90m"
  else
    [ "${ARENA_MOVE:2:2}" = ${POSXS:SEQ%8:1}$((SEQ/8+1)) ] && echo -en "\e[103;30m$PIECE\e[43;90m" || echo -n "\e[30m$PIECE\e[90m"
  fi
}

function color {
  [ "$1" = Red ] && echo -n '\e[31m⬤ \e[0m'
  [ "$1" = Black ] && echo -n '◯ '
}

POSXS="ABCDEFGH"
ENAMES="KAERHCPkaerhcp"
CNAMES="帥仕相俥傌炮兵將士象車馬包卒"
for i in {0..13} ; do
  ENAME="${ENAMES:$i:1}"
  CNAME="${CNAMES:$i:1}"
  ARENA_BOARD=${ARENA_BOARD//$ENAME/$CNAME}
done

[ -z "$ARENA_COLOR1" ] && PLAYER1="？" || PLAYER1=`color $ARENA_COLOR1`
[ -z "$ARENA_COLOR2" ] && PLAYER2="？" || PLAYER2=`color $ARENA_COLOR2`
if [ $((ARENA_MOVENO%2)) -eq 1 ] ; then # check if player1's turn
  if [ -z "$ARENA_STATUS" ] ; then
    PLAYER=""
    PLAYER1=$PLAYER1"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    PLAYER=""
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "$ARENA_STATUS" = "MIDDLE WINS !" ] ; then
    PLAYER="$ARENA_PLAYER2 $PLAYER2"
    PLAYER1=$PLAYER1" "
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    PLAYER="$ARENA_PLAYER1 $PLAYER1"
    PLAYER1=$PLAYER1"*"
  else
    PLAYER="$ARENA_PLAYER2 $PLAYER2"
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER2=$PLAYER2" "
else
  if [ -z "$ARENA_STATUS" ] ; then
    PLAYER=""
    PLAYER2=$PLAYER2"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    PLAYER=""
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "$ARENA_STATUS" = "MIDDLE WINS !" ] ; then
    PLAYER="$ARENA_PLAYER1 $PLAYER1"
    PLAYER2=$PLAYER2" "
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    PLAYER="$ARENA_PLAYER2 $PLAYER2"
    PLAYER2=$PLAYER2"*"
  elif [ "${ARENA_STATUS:0:6}" = "Choose" ] ; then
    PLAYER="\e[95m$ARENA_STATUS"
    PLAYER2=$PLAYER2"*"
    ARENA_STATUS=""
  else
    PLAYER="$ARENA_PLAYER1 $PLAYER1"
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER1=$PLAYER1" "
fi

DEADS="${ARENA_BOARD:33}"
REDDEAD=""
BLACKDEAD=""
i=0
while [ $i -lt ${#DEADS} ] ; do
  DEAD=${DEADS:i:1}
  CNAMEX=${CNAMES%%${DEAD}*}
  [ ${#CNAMEX} -lt 7 ] && REDDEAD=$REDDEAD$DEAD || BLACKDEAD=$BLACKDEAD$DEAD
  let i++
done

if [ "${ARENA_THEME,,}" = log ] ; then
  [ -n "$ARENA_STATUS" ] && echo "$PLAYER $ARENA_STATUS $ARENA_MOVENO Moves."
else # default
  clear
  echo -e "  \e[90;43m ┏━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┓ \e[0m\t\e[94mFarm Board Xiang Qi\e[0m"
  echo -e "４\e[90;43m ┃ `piece 24`│ `piece 25`│ `piece 26`│ `piece 27`│ `piece 28`│ `piece 29`│ `piece 30`│ `piece 31`┃ \e[0m"
  echo -e "  \e[90;43m ┠───┼───┼───╆━━━╈━━━╅───┼───┼───┨ \e[0m\t$ARENA_PLAYER1 $PLAYER1 vs. $ARENA_PLAYER2 $PLAYER2"
  echo -e "３\e[90;43m ┃ `piece 16`│ `piece 17`│ `piece 18`┃ `piece 19`┃ `piece 20`┃ `piece 21`│ `piece 22`│ `piece 23`┃ \e[0m"
  echo -e "  \e[90;43m ┠───┼───┼───╊━━━╋━━━╉───┼───┼───┨ \e[0m\t$PLAYER \e[95m$ARENA_STATUS\e[0m"
  echo -e "２\e[90;43m ┃ `piece 8`│ `piece 9`│ `piece 10`┃ `piece 11`┃ `piece 12`┃ `piece 13`│ `piece 14`│ `piece 15`┃ \e[0m"
  echo -e "  \e[90;43m ┠───┼───┼───╄━━━╇━━━╃───┼───┼───┨ \e[0m\t▥ : \e[107;31m$REDDEAD\e[0m"
  echo -e "１\e[90;43m ┃ `piece 0`│ `piece 1`│ `piece 2`│ `piece 3`│ `piece 4`│ `piece 5`│ `piece 6`│ `piece 7`┃ \e[0m\t    \e[107;30m$BLACKDEAD\e[0m"
  echo -e "  \e[90;43m ┗━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┛ \e[0m"
  echo -en "     Ａ  Ｂ  Ｃ  Ｄ  Ｅ  Ｆ  Ｇ  Ｈ  \tMove No. $ARENA_MOVENO: \e[93m"
fi
