#!/usr/bin/env bash
# CC0, Kerwin Hui <kommodorekerz@gmail.com>, 2017
# this AI is suicidal greedy
# the logic says it is willing to sacrifice K for a p.

# value of pieces according to oracle:
# P=A=1, E=2, H=C=(4 to 5), R=9, K=infinity
# we use 5 here for H and C.

# AI preference: capture > drop > move
# within capture, prefer capturing high value piece
# within drop, prefer dropping high value piece

MOVESNEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"` # next valid moves

POSXS="ABCDEFGHJK"
FILTERED_MOVES=""
DROP_MOVES=""
is_capture=0 # store value of piece captured in FILTERED_MOVES; for K we take shortcut

for test_move in ${MOVESNEXT}
do
	landing_pos=$((${test_move:3:1}*10-10))
	# test landing position to see if it is capture
	for x in {0..9}
	do
		if [ "${test_move:2:1}" = "${POSXS:x:1}" ]
		then
			landing_pos=$((landing_pos + x))
		fi
	done
	if [ "${test_move:0:1}" = "X" ]
	then
		DROP_MOVES="${DROP_MOVES}${test_move} "
	fi
	case "${ARENA_BOARD:landing_pos:1}" in
		"_")
			[ "$is_capture" = "0" ] && FILTERED_MOVES="${FILTERED_MOVES}${test_move} "
			;;
		"P"|"p"|"A"|"a")
			if [ "$is_capture" = "0" ]
			then
				is_capture="1"
				FILTERED_MOVES="${test_move} "
			elif [ ${is_capture} = "1" ]
			then
				FILTERED_MOVES="${FILTERED_MOVES}${test_move} "
			fi
			;;
		"E"|"e")
			if [ "$is_capture" -lt "2" ]
			then
				is_capture="2"
				FILTERED_MOVES="${test_move} "
			elif [ ${is_capture} = "2" ]
			then
				FILTERED_MOVES="${FILTERED_MOVES}${test_move} "
			fi
			;;
		"H"|"h"|"C"|"c")
			if [ "$is_capture" -lt "5" ]
			then
				is_capture="5"
				FILTERED_MOVES="${test_move} "
			elif [ ${is_capture} = "5" ]
			then
				FILTERED_MOVES="${FILTERED_MOVES}${test_move} "
			fi
			;;
		"R"|"r")
			if [ "$is_capture" -lt "9" ]
			then
				is_capture="9"
				FILTERED_MOVES="${test_move} "
			elif [ ${is_capture} = "9" ]
			then
				FILTERED_MOVES="${FILTERED_MOVES}${test_move} "
			fi
			;;
		"K"|"k")
			echo ${test_move}
			exit 0
			;;
		*)
			#shouldn't be here!
			;;
	esac
done
if [ -n "${DROP_MOVES}" -a "$is_capture" = "0" ]
then
	# sort drop pieces
	# drop PAEHCR
	FILTERED_MOVES=${DROP_MOVES}
	# only P/A?
	DROP_MOVES=${DROP_MOVES//XP?? /}
	DROP_MOVES=${DROP_MOVES//Xp?? /}
	DROP_MOVES=${DROP_MOVES//XA?? /}
	DROP_MOVES=${DROP_MOVES//Xa?? /}
	if [ -n "${DROP_MOVES}" ]
	then
		# drop EHCR
		FILTERED_MOVES=${DROP_MOVES}
		# only E?
		DROP_MOVES=${DROP_MOVES//XE?? /}
		DROP_MOVES=${DROP_MOVES//Xe?? /}
		if [ -n "${DROP_MOVES}" ]
		then
			# drop HCR
			FILTERED_MOVES=${DROP_MOVES}
			# any R left?
			DROP_MOVES=${DROP_MOVES//XH?? /}
			DROP_MOVES=${DROP_MOVES//Xh?? /}
			DROP_MOVES=${DROP_MOVES//XC?? /}
			DROP_MOVES=${DROP_MOVES//Xc?? /}
			if [ -n "${DROP_MOVES}" ]
			then
				# drop R
				FILTERED_MOVES=${DROP_MOVES}
			fi
		fi
	fi
fi

MOVESNO=$((${#FILTERED_MOVES}/5))
MOVE=${FILTERED_MOVES:(RANDOM%MOVESNO)*5:4}

echo ${MOVE}
