#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
function piece {
  SEQ=$1
  PIECE=${ARENA_BOARD:SEQ:1}
  if [ $PIECE = _ ] ; then
    case $SEQ in
      0) PIECE="╚═" ;;
      [1-8]) PIECE="╧═" ;;
      9) PIECE="╝ " ;;
      [1-7]0) PIECE="╟─" ;;
      [1-7][123678]) PIECE="┼─" ;;
      [1-7]4) PIECE="┤ " ;;
      [1-7]5) PIECE="├─" ;;
      [1-7]9) PIECE="╢ " ;;
      80) PIECE="╔═" ;;
      8[1-8]) PIECE="╤═" ;;
      89) PIECE="╗ " ;;
    esac
    [ "${ARENA_MOVE:0:2}" = ${POSXS:SEQ%10:1}$((SEQ/10+1)) ] && PIECE="\033[2m$PIECE\033[0m"
  else
    [ "${ARENA_MOVE:2:2}" = ${POSXS:SEQ%10:1}$((SEQ/10+1)) ] && PIECE="\033[7m$PIECE\033[0m"
  fi
  if [ $((SEQ%10)) -ne 9 ] ; then
    if [ $((SEQ/10%8)) -eq 0 ] ; then
      PIECE="$PIECE═"
    elif [ $((SEQ%10)) -ne 4 ] ; then
      PIECE="$PIECE─"
    else
      PIECE="$PIECE "
    fi
  fi
  echo -en "$PIECE" # need quote
}

POSXS="ABCDEFGHJK"
ENAMES="KAERHCPkaerhcp"
CNAMES="帥仕相俥傌炮兵將士象車馬包卒"
for i in {0..13} ; do
  ENAME="${ENAMES:$i:1}"
  CNAME="${CNAMES:$i:1}"
  ARENA_BOARD=${ARENA_BOARD//$ENAME/$CNAME}
done

PLAYER1="(Red)"
PLAYER2="(Black)"
if [ $((ARENA_MOVENO%2)) -eq 1 ] ; then # check if player1's turn
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER1=$PLAYER1"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1"*"
  else
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER1=$PLAYER1" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER2=$PLAYER2" "
else
  if [ -z "$ARENA_STATUS" ] ; then
    MESSAGE=""
    PLAYER2=$PLAYER2"*"
  elif  [ "$ARENA_STATUS" = "DRAW GAME !" ] ; then
    MESSAGE="${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  elif  [ "${ARENA_STATUS}" = "MIDDLE WINS !" ] ; then
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
  elif [ "${ARENA_STATUS:0:7}" = INVALID -o "${ARENA_STATUS:0:7}" = ILLEGAL ] ; then
    MESSAGE="${ARENA_PLAYER2}${PLAYER2} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2"*"
  else
    MESSAGE="${ARENA_PLAYER1}${PLAYER1} ${ARENA_STATUS}"
    PLAYER2=$PLAYER2" "
    ARENA_MOVENO=$((ARENA_MOVENO-1))
  fi
  PLAYER1=$PLAYER1" "
fi

DEADS="${ARENA_BOARD:91}"
REDDROPS=""
REDCODES=""
BLACKDROPS=""
BLACKCODES=""
i=0
while [ $i -lt ${#DEADS} ] ; do
  DEAD=${DEADS:i:1}
  CNAMEX=${CNAMES%%${DEAD}*}
  if [ ${#CNAMEX} -lt 7 ] ; then
    BLACKDROPS=${BLACKDROPS}${CNAMES:${#CNAMEX}+7:1}
    BLACKCODES="${BLACKCODES} ${ENAMES:${#CNAMEX}:1}"
  else
    REDDROPS=${REDDROPS}${CNAMES:${#CNAMEX}-7:1}
    REDCODES="${REDCODES} ${ENAMES:${#CNAMEX}-7:1}"
  fi
  let i++
done

if [ "${ARENA_THEME,,}" = log ] ; then
  [ -n "$ARENA_STATUS" ] && echo "$MESSAGE $ARENA_MOVENO Moves."
else # default
  POSY="１２３４５６７８９"
  clear
  for y in {8..0} ; do
    echo -n ${POSY:y:1}" "
    for x in {0..9} ; do
      POS=$((y*10+x))
      echo -n "`piece $POS`" # need quote
    done
    case $y in
      8) echo -e "\tShuai Qi" ;;
      6) echo -e "\t${ARENA_PLAYER1}${PLAYER1} vs. ${ARENA_PLAYER2}${PLAYER2}" ;;
      5) echo -e "\t${MESSAGE}" ;;
      4) echo -e "\t    ${REDCODES}" ;;
      3) echo -e "\tＸ: ${REDDROPS}" ;;
      2) echo -e "\t    ${BLACKDROPS}" ;;
      1) echo -e "\t    ${BLACKCODES}" ;;
      *) echo ;;
    esac
  done
  echo -en "   Ａ Ｂ Ｃ Ｄ Ｅ Ｆ Ｇ Ｈ Ｊ Ｋ\tMove No. ${ARENA_MOVENO}: "
fi
