#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
POSXS="ABCDEFGH" # X positions of board
BOARDNEXT=""
while [ -z "$BOARDNEXT" ] ; do
  MOVE=${POSXS:RANDOM%8:1}$((RANDOM%4+1))${POSXS:RANDOM%8:1}$((RANDOM%4+1))
  BOARDNEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_board"`
done
echo "${MOVE}"
