#!/usr/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018
if [ $ARENA_MOVENO -eq 0 ] ; then
  [ $((RANDOM%2)) -eq 0 ] && echo "Red" || echo "Black"
  exit
fi

MOVESNEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"` # next valid moves
MOVESNO=$((${#MOVESNEXT}/5))
MOVE=${MOVESNEXT:(RANDOM%MOVESNO)*5:4}
echo "$MOVE"