#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2018
MOVESNEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"` # next valid moves
if [ -z "$MOVESNEXT" ] ; then
  MOVE=""
else
  MOVESNO=$((${#MOVESNEXT}/5))
  MOVE=${MOVESNEXT:(RANDOM%MOVESNO)*5:4}
fi
echo "$MOVE"
