#!/bin/bash
# CC0, Wei-Lun Chao <bluebat@member.fsf.org>, 2017
MOVESNEXT=`"$DATADIR/uis/$ARENA_GAME/get_valid_moves"` # next valid moves
if [ -z "$MOVESNEXT" ] ; then
  ARENA_MOVE=""
else
  MOVEINDEX=$((${#MOVESNEXT}/5))
  ARENA_MOVE=${MOVESNEXT:(RANDOM%MOVEINDEX)*5:4}
fi
echo "${ARENA_MOVE}"
